queuemanager:
  name: mq-quickstart
  spec:
    license:
      accept: true
      license: L-VEMB-RABZSN
      use: NonProduction
    queueManager:
      name: QUICKSTART
      availability:
        type: SingleInstance
      storage:
        queueManager:
          type: persistent-claim
          size: 1Gi
          class: ocs-storagecluster-ceph-rbd
    version: 10.0.0.0-r1
    web:
      enabled: false
