global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-VEMB-RABZSN
      replicas: 1
      version: 16.2.0
